Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
results_generator = arxiv.Client(
  page_size=1000,
  delay_seconds=3,
  num_retries=3
).get(arxiv.Search(
  query='"quantum dots"',
  id_list=[],
  sort_by=arxiv.SortCriterion.Relevance,
  sort_order=arxiv.SortOrder.Descending,
))

quantum_dots = []
for paper in results_generator:
  # You could do per-paper analysis here; for now, just collect them in a list.
  quantum_dots.append(paper)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mUnexpectedEmptyPageError[0m                  Traceback (most recent call last)
[0;32m/tmp/ipykernel_1922/3426556834.py[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m [0;34m[0m[0m
[1;32m     12[0m [0mquantum_dots[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 13[0;31m [0;32mfor[0m [0mpaper[0m [0;32min[0m [0mresults_generator[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m   [0;31m# You could do per-paper analysis here; for now, just collect them in a list.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m   [0mquantum_dots[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mpaper[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/arxiv/arxiv.py[0m in [0;36mresults[0;34m(self, search)[0m
[1;32m    560[0m             ))
[1;32m    561[0m             [0mpage_url[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_format_url[0m[0;34m([0m[0msearch[0m[0;34m,[0m [0moffset[0m[0;34m,[0m [0mpage_size[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 562[0;31m             [0mfeed[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_parse_feed[0m[0;34m([0m[0mpage_url[0m[0;34m,[0m [0mfirst_page[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    563[0m             [0;32mif[0m [0mfirst_page[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    564[0m                 [0;31m# NOTE: this is an ugly fix for a known bug. The totalresults[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/arxiv/arxiv.py[0m in [0;36m_parse_feed[0;34m(self, url, first_page)[0m
[1;32m    643[0m         [0;31m# Feed was never returned in self.num_retries tries. Raise the last[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    644[0m         [0;31m# exception encountered.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 645[0;31m         [0;32mraise[0m [0merr[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    646[0m [0;34m[0m[0m
[1;32m    647[0m [0;34m[0m[0m

[0;31mUnexpectedEmptyPageError[0m: Page of results was unexpectedly empty (http://export.arxiv.org/api/query?search_query=%22quantum+dots%22&id_list=&sortBy=relevance&sortOrder=descending&start=1060&max_results=1000)
UnexpectedEmptyPageError: Page of results was unexpectedly empty (http://export.arxiv.org/api/query?search_query=%22quantum+dots%22&id_list=&sortBy=relevance&sortOrder=descending&start=1060&max_results=1000)

