Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 64, in single_nb_execution
    **kwargs,
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/jupyter_core/utils/__init__.py", line 98, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nbclient/client.py", line 706, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
results_generator = arxiv.Client(
  page_size=1000,
  delay_seconds=3,
  num_retries=3
).results(arxiv.Search(
  query='"quantum dots"',
  id_list=[],
  sort_by=arxiv.SortCriterion.Relevance,
  sort_order=arxiv.SortOrder.Descending,
))

quantum_dots = []
for paper in results_generator:
  # You could do per-paper analysis here; for now, just collect them in a list.
  quantum_dots.append(paper)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mUnexpectedEmptyPageError[0m                  Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m_parse_feed[0;34m(self, url, first_page, _try_index)[0m
[1;32m    625[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 626[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m__try_parse_feed[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mfirst_page[0m[0;34m=[0m[0mfirst_page[0m[0;34m,[0m [0mtry_index[0m[0;34m=[0m[0m_try_index[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    627[0m         except (

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m__try_parse_feed[0;34m(self, url, first_page, try_index)[0m
[1;32m    666[0m         [0;32mif[0m [0mlen[0m[0;34m([0m[0mfeed[0m[0;34m.[0m[0mentries[0m[0;34m)[0m [0;34m==[0m [0;36m0[0m [0;32mand[0m [0;32mnot[0m [0mfirst_page[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 667[0;31m             [0;32mraise[0m [0mUnexpectedEmptyPageError[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mtry_index[0m[0;34m,[0m [0mfeed[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    668[0m [0;34m[0m[0m

[0;31mUnexpectedEmptyPageError[0m: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%22quantum+dots%22&id_list=&sortBy=relevance&sortOrder=descending&start=8000&max_results=1000)

During handling of the above exception, another exception occurred:

[0;31mUnexpectedEmptyPageError[0m                  Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m_parse_feed[0;34m(self, url, first_page, _try_index)[0m
[1;32m    625[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 626[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m__try_parse_feed[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mfirst_page[0m[0;34m=[0m[0mfirst_page[0m[0;34m,[0m [0mtry_index[0m[0;34m=[0m[0m_try_index[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    627[0m         except (

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m__try_parse_feed[0;34m(self, url, first_page, try_index)[0m
[1;32m    666[0m         [0;32mif[0m [0mlen[0m[0;34m([0m[0mfeed[0m[0;34m.[0m[0mentries[0m[0;34m)[0m [0;34m==[0m [0;36m0[0m [0;32mand[0m [0;32mnot[0m [0mfirst_page[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 667[0;31m             [0;32mraise[0m [0mUnexpectedEmptyPageError[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mtry_index[0m[0;34m,[0m [0mfeed[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    668[0m [0;34m[0m[0m

[0;31mUnexpectedEmptyPageError[0m: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%22quantum+dots%22&id_list=&sortBy=relevance&sortOrder=descending&start=8000&max_results=1000)

During handling of the above exception, another exception occurred:

[0;31mUnexpectedEmptyPageError[0m                  Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m_parse_feed[0;34m(self, url, first_page, _try_index)[0m
[1;32m    625[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 626[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m__try_parse_feed[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mfirst_page[0m[0;34m=[0m[0mfirst_page[0m[0;34m,[0m [0mtry_index[0m[0;34m=[0m[0m_try_index[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    627[0m         except (

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m__try_parse_feed[0;34m(self, url, first_page, try_index)[0m
[1;32m    666[0m         [0;32mif[0m [0mlen[0m[0;34m([0m[0mfeed[0m[0;34m.[0m[0mentries[0m[0;34m)[0m [0;34m==[0m [0;36m0[0m [0;32mand[0m [0;32mnot[0m [0mfirst_page[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 667[0;31m             [0;32mraise[0m [0mUnexpectedEmptyPageError[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mtry_index[0m[0;34m,[0m [0mfeed[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    668[0m [0;34m[0m[0m

[0;31mUnexpectedEmptyPageError[0m: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%22quantum+dots%22&id_list=&sortBy=relevance&sortOrder=descending&start=8000&max_results=1000)

During handling of the above exception, another exception occurred:

[0;31mUnexpectedEmptyPageError[0m                  Traceback (most recent call last)
[0;32m/tmp/ipykernel_2172/2762950194.py[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m [0;34m[0m[0m
[1;32m     12[0m [0mquantum_dots[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 13[0;31m [0;32mfor[0m [0mpaper[0m [0;32min[0m [0mresults_generator[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m   [0;31m# You could do per-paper analysis here; for now, just collect them in a list.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m   [0mquantum_dots[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mpaper[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m_results[0;34m(self, search, offset)[0m
[1;32m    598[0m                 [0;32mbreak[0m[0;34m[0m[0;34m[0m[0m
[1;32m    599[0m             [0mpage_url[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_format_url[0m[0;34m([0m[0msearch[0m[0;34m,[0m [0moffset[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mpage_size[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 600[0;31m             [0mfeed[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_parse_feed[0m[0;34m([0m[0mpage_url[0m[0;34m,[0m [0mfirst_page[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    601[0m [0;34m[0m[0m
[1;32m    602[0m     [0;32mdef[0m [0m_format_url[0m[0;34m([0m[0mself[0m[0;34m,[0m [0msearch[0m[0;34m:[0m [0mSearch[0m[0;34m,[0m [0mstart[0m[0;34m:[0m [0mint[0m[0;34m,[0m [0mpage_size[0m[0;34m:[0m [0mint[0m[0;34m)[0m [0;34m->[0m [0mstr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m_parse_feed[0;34m(self, url, first_page, _try_index)[0m
[1;32m    632[0m             [0;32mif[0m [0m_try_index[0m [0;34m<[0m [0mself[0m[0;34m.[0m[0mnum_retries[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    633[0m                 [0mlogger[0m[0;34m.[0m[0mdebug[0m[0;34m([0m[0;34m"Got error (try %d): %s"[0m[0;34m,[0m [0m_try_index[0m[0;34m,[0m [0merr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 634[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_parse_feed[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mfirst_page[0m[0;34m=[0m[0mfirst_page[0m[0;34m,[0m [0m_try_index[0m[0;34m=[0m[0m_try_index[0m [0;34m+[0m [0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    635[0m             [0mlogger[0m[0;34m.[0m[0mdebug[0m[0;34m([0m[0;34m"Giving up (try %d): %s"[0m[0;34m,[0m [0m_try_index[0m[0;34m,[0m [0merr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    636[0m             [0;32mraise[0m [0merr[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m_parse_feed[0;34m(self, url, first_page, _try_index)[0m
[1;32m    632[0m             [0;32mif[0m [0m_try_index[0m [0;34m<[0m [0mself[0m[0;34m.[0m[0mnum_retries[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    633[0m                 [0mlogger[0m[0;34m.[0m[0mdebug[0m[0;34m([0m[0;34m"Got error (try %d): %s"[0m[0;34m,[0m [0m_try_index[0m[0;34m,[0m [0merr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 634[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_parse_feed[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mfirst_page[0m[0;34m=[0m[0mfirst_page[0m[0;34m,[0m [0m_try_index[0m[0;34m=[0m[0m_try_index[0m [0;34m+[0m [0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    635[0m             [0mlogger[0m[0;34m.[0m[0mdebug[0m[0;34m([0m[0;34m"Giving up (try %d): %s"[0m[0;34m,[0m [0m_try_index[0m[0;34m,[0m [0merr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    636[0m             [0;32mraise[0m [0merr[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m_parse_feed[0;34m(self, url, first_page, _try_index)[0m
[1;32m    632[0m             [0;32mif[0m [0m_try_index[0m [0;34m<[0m [0mself[0m[0;34m.[0m[0mnum_retries[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    633[0m                 [0mlogger[0m[0;34m.[0m[0mdebug[0m[0;34m([0m[0;34m"Got error (try %d): %s"[0m[0;34m,[0m [0m_try_index[0m[0;34m,[0m [0merr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 634[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_parse_feed[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mfirst_page[0m[0;34m=[0m[0mfirst_page[0m[0;34m,[0m [0m_try_index[0m[0;34m=[0m[0m_try_index[0m [0;34m+[0m [0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    635[0m             [0mlogger[0m[0;34m.[0m[0mdebug[0m[0;34m([0m[0;34m"Giving up (try %d): %s"[0m[0;34m,[0m [0m_try_index[0m[0;34m,[0m [0merr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    636[0m             [0;32mraise[0m [0merr[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m_parse_feed[0;34m(self, url, first_page, _try_index)[0m
[1;32m    634[0m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_parse_feed[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mfirst_page[0m[0;34m=[0m[0mfirst_page[0m[0;34m,[0m [0m_try_index[0m[0;34m=[0m[0m_try_index[0m [0;34m+[0m [0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    635[0m             [0mlogger[0m[0;34m.[0m[0mdebug[0m[0;34m([0m[0;34m"Giving up (try %d): %s"[0m[0;34m,[0m [0m_try_index[0m[0;34m,[0m [0merr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 636[0;31m             [0;32mraise[0m [0merr[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    637[0m [0;34m[0m[0m
[1;32m    638[0m     def __try_parse_feed(

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m_parse_feed[0;34m(self, url, first_page, _try_index)[0m
[1;32m    624[0m         """
[1;32m    625[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 626[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m__try_parse_feed[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mfirst_page[0m[0;34m=[0m[0mfirst_page[0m[0;34m,[0m [0mtry_index[0m[0;34m=[0m[0m_try_index[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    627[0m         except (
[1;32m    628[0m             [0mHTTPError[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/arxiv/__init__.py[0m in [0;36m__try_parse_feed[0;34m(self, url, first_page, try_index)[0m
[1;32m    665[0m         [0mfeed[0m [0;34m=[0m [0mfeedparser[0m[0;34m.[0m[0mparse[0m[0;34m([0m[0mresp[0m[0;34m.[0m[0mcontent[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    666[0m         [0;32mif[0m [0mlen[0m[0;34m([0m[0mfeed[0m[0;34m.[0m[0mentries[0m[0;34m)[0m [0;34m==[0m [0;36m0[0m [0;32mand[0m [0;32mnot[0m [0mfirst_page[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 667[0;31m             [0;32mraise[0m [0mUnexpectedEmptyPageError[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mtry_index[0m[0;34m,[0m [0mfeed[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    668[0m [0;34m[0m[0m
[1;32m    669[0m         [0;32mif[0m [0mfeed[0m[0;34m.[0m[0mbozo[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mUnexpectedEmptyPageError[0m: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%22quantum+dots%22&id_list=&sortBy=relevance&sortOrder=descending&start=8000&max_results=1000)

